package org.example.app.entity.book;

import com.fasterxml.jackson.annotation.JsonIgnore;
import io.swagger.annotations.ApiModelProperty;
import lombok.Data;
import org.example.app.entity.enums.Rating;

import javax.persistence.*;
import java.util.List;

@Data
@Entity
@Table(name = "rate")
public class Rate {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(columnDefinition = "INT NOT NULL AUTO_INCREMENT")
    @ApiModelProperty("id generated by db automatically")
    private Integer id;

    @Column(name= "value", columnDefinition = "INT")
    private Integer value;

    @ManyToMany(mappedBy = "rates")
    @JsonIgnore
    private List<Book> books;

    @Transient
    private Rating rating;

    @PostLoad
    void populateRangeAttrAfterLoad() {
        if (value > 0) {
            this.rating = Rating.of(value);
        }
    }

    @PrePersist
    void populateRangeAttrBeforePersist() {
        if (rating != null) {
            this.value = rating.getValue();
        }
    }
}
